# Generated by Django 5.1.1 on 2024-09-05 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(verbose_name='طول جغرافیایی')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ثبت')),
                ('timestamp_shamsi', models.CharField(blank=True, max_length=20, verbose_name='تاریخ و ساعت شمسی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
            },
        ),
    ]
