# Generated by Django 5.1.1 on 2024-09-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='battery_level',
            field=models.FloatField(blank=True, null=True, verbose_name='مقدار شارژ باتری'),
        ),
        migrations.AddField(
            model_name='location',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='سرعت'),
        ),
    ]
